### ISSUE TITLE
Slightly confusing coloring with JS Custom

### ISSUE THREAD

**Issue by dsl101** [dcasella/monokai-plusplus#11]
I've just switch syntax to JS Custom, as all my old JS syntaxes were quite out of date. I _was_ using Monokai SL, but it didn't have function call coloring for some reason, so I also switched to Monokai++.

I've noticed some rather odd examples—are these as expected? I'm also unsure whether this is a theme or syntax issue. Let me know if the JS Custom scopes are important—I can add those too.

Example 1 (why is `rtdbOptions` highlighted in the second line?):
![image](https://user-images.githubusercontent.com/900542/73170932-7f982a80-40f7-11ea-85d9-e12d583293c4.png)

Example 2 (all parentheses and braces are green after `.then`):
![image](https://user-images.githubusercontent.com/900542/73171013-a8b8bb00-40f7-11ea-8549-d0f385445755.png)

**Comment by dcasella** [comment]
This is usually due to syntax highlighting reporting non-standard TextMate scopes; this is why I have a "Language specific" section in the theme's code.

Built-in Javascript syntax highlighting works fine; to reproduce locally I'd need you to tell me which extension and settings you're using.

**Comment by dsl101** [comment]
By extension and settings, other than JS Custom (https://github.com/Thom1729/Sublime-JS-Custom) with default settings, I'm not sure what else you need.

In the first example above, the first line shows `rtdbOptions` as `source.js.default variable.other.readwrite.js` and `.wait` as `source.js.default meta.property.object.js`.

In the second line, `rtdbOptions` is `source.js.default meta.function.declaration.js support.class.js` and `.reset` is `source.js.default meta.function.declaration.js entity.name.function.js variable.other.readwrite.js`

If you think that's not right, I can open a ticket with JS Custom, but I'm a bit caught between the two figuring out what is should be.

If it helps to get the scopes in the second example, let me know and I can get them out.

Many thanks!

**Comment by dsl101** [comment]
Also, I just uninstalled and reinstalled JS Next from package control, and weirdly the original problem I was trying to solve by moving to JS Custom has gone away! So, no problem if this isn't a priority right now. I'm happy to test / provide info anyway. There is only 1 thing in JS Next that isn't working right now, and I'll try to make another PR if I get it fixed.
