### ISSUE TITLE
Latest JavaScript scopes and highlighting

### ISSUE THREAD

**Issue by dsl101** [dcasella/monokai-plusplus#14]
Hi again—looks like I'm going to have to ditch JS Next as my syntax highlighter, as it's unmaintained, and for some reason won't work inside Vue component script tags. The way it labels scopes seems to work very nicely with Monokai++, but the built-in JavaScript syntax in ST3 doesn't work as well. For example, take this snippet using the built-in highlighter:

    export default {
      thing: 0,
      otherThing: null,
      finalThing: undefined
    }

    import store from 'vuex'

    const loadTab = (to, from, next) => {
      console.group('Event')
      console.log('starting:', store.state.loadingEvent)
      console.log('to.name:', to.name)
      console.log('from:', from)
      console.log('next:', next)
      console.log('store.getters.isAdmin():', store.getters.isAdmin())
      console.groupEnd()

      if (store.getters.isAdmin({ eventId: to.params.eventId }) && to.name === 'Event') {
        const lastTab = store.getters.lastTab(to.params.event) || 'dashboard'
        console.log(lastTab)
      }

    }

    loadTab()

Using the latest theme file from github (I just copied it as a local theme):

![image](https://user-images.githubusercontent.com/900542/73832526-3a16e400-4800-11ea-84b2-64eefa7b7b13.png)

Things I notice and can't stop noticing :) (I've included the scopes where I can):

- Object string keys not in yellow (`source.js meta.export.js meta.object-literal.js meta.object-literal.key.js`)
- Arrow function definition not green (`source.js meta.function.declaration.js entity.name.function.js variable.other.readwrite.js`)
- Object braces (`{` & `}`) in parameter for `isAdmin()` are green but should be white (`source.js meta.function.js meta.block.js meta.conditional.js meta.group.js meta.function-call.method.js meta.group.js meta.object-literal.js punctuation.section.block.begin.js` and `... punctuation.section.block.end.js`)
- `eventId:` object key is green, should be yellow (`source.js meta.function.js meta.block.js meta.conditional.js meta.group.js meta.function-call.method.js meta.group.js meta.object-literal.js meta.object-literal.key.js`)

Really hoping you're able to fix these, and then I can get rid of my weird alternative JS highlighters and just stick with the plain one, which does work inside Vue SFCs.

**Comment by dsl101** [comment]
And to make things even more confusing, here's some of that code _inside a Vue SFC_, rather than as a plain `.js` file:

![image](https://user-images.githubusercontent.com/900542/73834043-ee196e80-4802-11ea-8aaf-76e91db16b8c.png)

Note some things on the `if(` line are now correctly coloured? The scopes are different here, I guess because of the embedded script, and crucially there's an extra scope on `eventId:`:

    text.html.vue
    source.js.embedded.html
    source.js
    meta.function.js
    meta.block.js
    meta.conditional.js
    meta.group.js
    meta.function-call.method.js
    meta.group.js
    meta.mapping.js
    meta.mapping.key.js
    string.unquoted.js

That last one isn't there in the plain `.js` file—guess that's a syntax highlighter issue, but it does look like v-s-h is not _just_ using the built-in version?

**Comment by dcasella** [comment]
For reference, here's a screenshot for the code you provided:
![image](https://user-images.githubusercontent.com/19588895/75165612-f4747980-5722-11ea-9228-ada4feabb60e.png)
