### ISSUE TITLE
Monokai++ with Volar extension

### ISSUE THREAD

**Issue by lacherogwu** [dcasella/monokai-plusplus#20]
When I use Monokai++ with Volar(Official vue extension), I don't get component s highlist and it just look same color of the HTML tag 
<img width="707" alt="image" src="https://user-images.githubusercontent.com/49835614/175882340-e68b59bd-87fb-4c52-bfb5-30e8363a454c.png">

When I use vetur(the previous vue extension) it is showing correctly
<img width="488" alt="image" src="https://user-images.githubusercontent.com/49835614/175882466-c6f61a61-cacc-403e-ae4b-e08b10253fff.png">

And also if I use Volar with any other color theme it's working great
<img width="565" alt="image" src="https://user-images.githubusercontent.com/49835614/175882803-0c673e67-fe02-40a5-8a52-2344058eef3e.png">

But I didn't find any other Color theme that looks good, I think Monokai++ has the best colors
I don't know if I should open an issue here or in Volar extension repo.

Thanks for your help!

**Comment by dcasella** [comment]
Hi,

Could you tell me one or more Color Themes that work as expected? I tried a few and couldn't fine one.
If other color themes work just fine I can patch it in Monokai++ without going upstream (Volar). 

Thanks

**Comment by lacherogwu** [comment]
https://marketplace.visualstudio.com/items?itemName=zhuangtongfa.Material-theme
This for e.g.

But actually, any other theme that I used worked just fine

Thank you very much for your help! appreciate it ❤️

**Comment by dcasella** [comment]
1.11.0 will soon be released (the mighty Marketplace is still processing the publication). Please let me know if it doesn't work correctly.

**Comment by lacherogwu** [comment]
All works, thanks!

**Comment by lacherogwu** [comment]
Hello, I've noticed a color change, is this intentional? 
The previous version colored looked much better, and now it's coloring many things in orange. see here
I added the version inside the pictures.
<img width="1396" alt="Screen Shot 2022-06-27 at 16 40 51" src="https://user-images.githubusercontent.com/49835614/175956249-2ec7d287-f62c-4d7a-b5d8-e32d8f8de5e6.png">
<img width="1435" alt="Screen Shot 2022-06-27 at 16 41 58" src="https://user-images.githubusercontent.com/49835614/175956278-fd5f73d9-e7ed-47ff-87ef-d37e863a48aa.png">

**Comment by dcasella** [comment]
Yes, this is intentional because of VS Code's semantic highlighting. It understands what is a parameter, a variable, a type, etc.
I believe it can be bothersome, but I mostly use Bash and Python nowadays so I can't comment on it yet.

I might change some colors back in the future.

**Comment by lacherogwu** [comment]
Okay thanks for your help, then I guess it will be better if you retrieve the changes to V1.10.0 since many users got affected because of this update and I guess they will prefer what was at V1.10.0

I think it's better not to have Vue3 semantic highlighting than to change the .js semantic highlighting 

Thanks!
