### ISSUE TITLE
mark occurrences highlight

### ISSUE THREAD

**Issue by LeonardAB** [dcasella/monokai-plusplus#5]
Hi, this is a very nice Monokai! I use it in VS code.
I have a question. How to change the color of mark occurrences highlight (when we put a cursor on a variable name for example, all occurrences of that name will be highlighted)?
It seems to be a bright red, I want to change it to a softer color. I tried to open Monokai++.tmTheme but I couldn't find any tag related to occurrences. 
I tried to override in the user-setting using 

` "workbench.colorCustomizations": {
        "editor.selectionHighlightBackground": "#804343",
        "editor.selectionBackground": "#804343"
}`

but still doesn't work. Could you please help? Thank you so much in advance.

**Comment by dcasella** [comment]
```
"workbench.colorCustomizations": {
    "editor.selectionHighlightBackground": "#804343"
}
```
seems to work fine on a fresh install of VS Code, as shown below:
![image](https://user-images.githubusercontent.com/19588895/33381185-91f8a760-d51d-11e7-8df6-295b5664dbb9.png)
I'm sorry, but I'm having trouble reproducing the problem.

I don't know if tmTheme settings are still supported though. The [wiki](https://github.com/Microsoft/vscode/wiki/Editor-decorations-&-colors) was last updated on Jan 21, and I'm pretty sure at least some of those don't work anymore.
