### ISSUE TITLE
Indent guides too dark

### ISSUE THREAD

**Issue by danielmcq** [dcasella/monokai-plusplus#6]
Would it be possible to make the color for the indent guides a bit lighter? They're nearly invisible in SublimeText3. Below are two screenshots which compare between the Monokai theme and the Monokai++ theme.

Monokai indent guides
![image](https://user-images.githubusercontent.com/212776/39723482-38efe670-5203-11e8-98d5-2919c0649cbf.png)

Monokai++ indent guides
![image](https://user-images.githubusercontent.com/212776/39723489-3d7e1d6a-5203-11e8-9edc-a9bdbb3f177a.png)

**Comment by dcasella** [comment]
Reasonable.
I made the guides the same color as invisible characters (e.g. spaces in the screenshots you provided).

**Comment by danielmcq** [comment]
Awesome! Thank you. I really enjoy this theme. That was just one minor annoyance I had.
