### ISSUE TITLE
Vue lang support

### ISSUE THREAD

**Issue by limeandcoconut** [dcasella/monokai-plusplus#8]
I've been wishing I could switch to this for a while but without Vue lang support I just can't. Any chance we could get that?

**Comment by dcasella** [comment]
Hi,
Which editor and syntax highlighter combination are you using?

I tested the following and they seem to work fine. 

#### VSCode

- [Vetur](https://marketplace.visualstudio.com/items?itemName=octref.vetur)

#### Sublime Text

- [Vue Syntax Highlight](https://packagecontrol.io/packages/Vue%20Syntax%20Highlight) (official, I guess?)
- [Vuejs Complete Package](https://packagecontrol.io/packages/Vuejs%20Complete%20Package)
  Equals and [v-bind quoted variables](https://vuejs.org/v2/guide/syntax.html#v-bind-Shorthand) are highlighted slightly differenly with this Syntax Highlighter.

Color schemes and syntax highlighters are two different pieces of the chain; you need to install a syntax highlighter for VueJS to "enable coloring" (I didn't know how else to phrase it 😄) on VueJS files.
