### ISSUE TITLE
Add diff highlighting

### ISSUE THREAD

**Issue by dsl101** [dcasella/monokai-plusplus#9]
Just switched to Monokai++ and really like it for most programming jobs. But, I've lost highlighting on diff files. The syntax higlighter is there, and I can see it's setting the scopes. But I guess there are no definitions in the theme. Any chance to add those?

**Comment by dsl101** [comment]
OK, I decided to dive in and see if I could make a start. I'll make a PR in case it's of use. It's good enough for me (just 3 stopes).

**Comment by dcasella** [comment]
PRs are sure welcome!
I should be able to find some time next week to work on it (PR or from scratch).

**Comment by dsl101** [comment]
Sorry, got distracted. I have the updated theme file locally installed, and works for me. I'll make a PR next week.

**Comment by dsl101** [comment]
OK—made a PR: https://github.com/dcasella/monokai-plusplus/pull/10
